language: python

sudo: true

services:
  - elasticsearch

python:
  - '3.4'
  - '3.5'
  - '3.6'

# commands to install dependencies
before_install:
  - "sudo apt-get install -y apt-transport-https"
  - "sudo apt-get install -y libemail-outlook-message-perl"

install:
  - "pip install -r requirements.txt"

before_script:
  - sleep 10

# commands to run samples
script:
  - "flake8 *.py parsedmarc/*.py"
  - "rstcheck --report warning README.rst"
  - "cd docs"
  - "make html"
  - "cd .."
  - "python tests.py"
  - "parsedmarc --save-aggregate samples/aggregate/*"
  - "parsedmarc --save-forensic samples/forensic/*"
  - "python setup.py sdist"
  - "python setup.py bdist_wheel"
