language: python

sudo: false

python:
  - '3.4'
  - '3.5'
  - '3.6'

# commands to install dependencies
install:
  - "pip install flake8 pytest-cov pytest coveralls"
  - "pip install -r requirements.txt"

# commands to run samples
script:
  - "flake8 *.py parsedmarc/*.py"
  - "rstcheck README.rst docs/index.rst"
  - "cd docs"
  - "make html"
  - "cd .."
  - "python tests.py"
  - "python setup.py bdist_wheel"
