language: python

dist: xenial
sudo: true

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

# commands to install dependencies
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y libemail-outlook-message-perl"
  - "curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.5.1.deb && sudo service elasticsearch restart"

install:
  - "pip install -r requirements.txt"

# commands to run samples
script:
  - "flake8 *.py parsedmarc/*.py"
  - "rstcheck --report warning README.rst"
  - "cd docs"
  - "make html"
  - "cd .."
  - "coverage run tests.py"
  - "python setup.py install"
  - "parsedmarc -c ci.ini samples/aggregate/*"
  - "parsedmarc -c ci.ini samples/forensic/*"
  - "python setup.py sdist"
  - "python setup.py bdist_wheel"

after_success:
  - "codecov"
