language: python

sudo: true

python:
  - '3.4'
  - '3.5'
  - '3.6'

# commands to install dependencies
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y libemail-outlook-message-perl"

install:
  - "pip install -r requirements.txt"

# commands to run samples
script:
  - "flake8 *.py parsedmarc/*.py"
  - "rstcheck --report warning README.rst"
  - "cd docs"
  - "make html"
  - "cd .."
  - "python tests.py"
  - "python setup.py sdist"
  - "python setup.py bdist_wheel"
